### PR TITLE
Added plugin and native ionic code

### PR DESCRIPTION
**Pull request by esgraham**
Added plugin code and native ionic code

### CODE REVIEW

**Comment by bsherwin** [comment]
Is there a reason we wouldn't be using an MIT License. Currently, Apache license.

**Comment by bsherwin** [comment]
Looks like we need to add `.DS_Store` to our .gitignore

**Comment by esgraham** [comment]
The gitignore file contained the cognitiveservices/plugin/.DS_Store.  Changed that line to just .DS_Store.

**Comment by esgraham** [comment]
Added an issue to review the correct licensing for the plugin.

**Comment by esgraham** [comment]
Issue #5

**Pull request merged**
